* ------------------------- COMANDOS TCL ------------------------ */
/* ---------------------- EJEMPLO TRANSACTIONS ------------------- */
/* --------------------------------------------------------------- */

CREATE DATABASE PRUEBAST;
USE PRUEBAST;

CREATE TABLE ALUMNOS(

	CODALU INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    FECHANACI DATE,
	ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NOTAF DOUBLE
);

SELECT * FROM ALUMNOS;

SET AUTOCOMMIT=0; /* DESACTIVAMOS EL COMMIT POR DEFECTO, PARA PODER DESHACER LO QUE REALICEMOS */

START TRANSACTION; 
BEGIN; /* COMENZAMOS LAS ACCIONES QUE VAMOS A CONTROLAR */

INSERT INTO ALUMNOS (NOMBRE,FECHANACI,NOTAF) VALUES 
('PEPE','2022-12-12',8.5); /* INSERTAMOS UN REGISTRO */ 

SAVEPOINT REGISTROS; /* PONEMOS UN PUNTO DE GRABACIÓN LLAMADO REGISTROS */

INSERT INTO ALUMNOS (NOMBRE,FECHANACI,NOTAF) VALUES 
('PEPITO','2022-11-12',6.5); /* INSERTAMOS OTRO REGISTRO */ 

ROLLBACK TO SAVEPOINT REGISTROS; /* DESHACEMOS LA ÚLTIMA INSERCIÓN */

ROLLBACK; /* DESHACEMOS TODO HASTA EL COMENTO DE COMIENZO BEGIN */
COMMIT; /* SE HACEMOS LAS DOS INSERCIONES SIN LOS ROLLBACK, Y EJECUTAMOS COMMIT, YA NO PODREMOS HACER ROLLBACK DE ESOS DATOS */
